/* istanbul ignore file */

export default Object.freeze({
    ".NET": ".NET",
    ".NET Core": ".NET Core",
    ".NET Entity Framework": ".NET Entity Framework",
    "Abap": "Abap",
    "Ada": "Ada",
    "Alpine": "Alpine",
    "Android": "Android",
    "Angular": "Angular",
    "Ansible": "Ansible",
    "Apache": "Apache",
    "Apollo": "Apollo",
    "Appium": "Appium",
    "ASP.NET": "ASP.NET",
    "ASP.NET Core": "ASP.NET Core",
    "Aurelia": "Aurelia",
    "AWS": "AWS",
    "Azure": "Azure",
    "Beego": "Beego",
    "Browserstack": "Browserstack",
    "C": "C",
    "C#": "C#",
    "C++": "C++",
    "Cassandra": "Cassandra",
    "CircleCI": "CircleCI",
    "Clojure": "Clojure",
    "Cobol": "Cobol",
    "CodeIgniter": "CodeIgniter",
    "CouchDB": "CouchDB",
    "CSS": "CSS",
    "Cypress": "Cypress",
    "D": "D",
    "Dart": "Dart",
    "DevOps": "DevOps",
    "Django": "Django",
    "Docker": "Docker",
    "Drupal": "Drupal",
    "Elasticsearch": "Elasticsearch",
    "Electron": "Electron",
    "Elixir": "Elixir",
    "EmberJS": "EmberJS",
    "Erlang": "Erlang",
    "ExpressJS": "ExpressJS",
    "F#": "F#",
    "FastAPI": "FastAPI",
    "Flask": "Flask",
    "Flutter": "Flutter",
    "Fortran": "Fortran",
    "Gatsby": "Gatsby",
    "Git": "Git",
    "Go": "Go",
    "Google Cloud": "Google Cloud",
    "Grafana": "Grafana",
    "Graphite": "Graphite",
    "GraphQL": "GraphQL",
    "Groovy": "Groovy",
    "GTK+": "GTK+",
    "H2": "H2",
    "Hadoop": "Hadoop",
    "Haskell": "Haskell",
    "HTML": "HTML",
    "IBM DB2": "IBM DB2",
    "iOS": "iOS",
    "Iris": "Iris",
    "Java": "Java",
    "JavaScript": "JavaScript",
    "Jenkins": "Jenkins",
    "Jest": "Jest",
    "Jira": "Jira",
    "JQuery": "JQuery",
    "Julia": "Julia",
    "Junit": "Junit",
    "Keras": "Keras",
    "Koa": "Koa",
    "Kotlin": "Kotlin",
    "Kubernetes": "Kubernetes",
    "Laravel": "Laravel",
    "Linux": "Linux",
    "LitElement": "LitElement",
    "Lua": "Lua",
    "MacOS": "MacOS",
    "MariaDB": "MariaDB",
    "Matlab": "Matlab",
    "Meteor": "Meteor",
    "Mocha": "Mocha",
    "MongoDB": "MongoDB",
    "MySQL": "MySQL",
    "NextJS": "NextJS",
    "Nginx": "Nginx",
    "NodeJS": "NodeJS",
    "NoSQL": "NoSQL",
    "Objective-C": "Objective-C",
    "OpenAI": "OpenAI",
    "OpenCL": "OpenCL",
    "OpenCV": "OpenCV",
    "OpenGL": "OpenGL",
    "Oracle Database": "Oracle Database",
    "Pascal": "Pascal",
    "Perl": "Perl",
    "Phoenix": "Phoenix",
    "PHP": "PHP",
    "PHPUnit": "PHPUnit",
    "Polymer": "Polymer",
    "PostgreSQL": "PostgreSQL",
    "Preact": "Preact",
    "Prolog": "Prolog",
    "Prometheus": "Prometheus",
    "Pytest": "Pytest",
    "Python": "Python",
    "PyTorch": "PyTorch",
    "Qt": "Qt",
    "R": "R",
    "RabbitMQ": "RabbitMQ",
    "React": "React",
    "React Native": "React Native",
    "Redis": "Redis",
    "Rholang": "Rholang",
    "Robot Framework": "Robot Framework",
    "Ruby": "Ruby",
    "Ruby on Rails": "Ruby on Rails",
    "Rust": "Rust",
    "Scala": "Scala",
    "Scheme": "Scheme",
    "Selenium": "Selenium",
    "Shell": "Shell",
    "Solidity": "Solidity",
    "Spring": "Spring",
    "Spring Boot": "Spring Boot",
    "SQL": "SQL",
    "SQL Server": "SQL Server",
    "Stimulus": "Stimulus",
    "Strapi": "Strapi",
    "Svelte": "Svelte",
    "Swift": "Swift",
    "Swing": "Swing",
    "Symfony": "Symfony",
    "Tensorflow": "Tensorflow",
    "Terraform": "Terraform",
    "TypeScript": "TypeScript",
    "Unity": "Unity",
    "Unreal Engine": "Unreal Engine",
    "VBA": "VBA",
    "VirtualBox": "VirtualBox",
    "Visual Basic": "Visual Basic",
    "VMWare": "VMWare",
    "VueJS": "VueJS",
    "Vyper": "Vyper",
    "WebdriverIO": "WebdriverIO",
    "Windows": "Windows",
    "WordPress": "WordPress",
    "Xamarin": "Xamarin",
    "Yii": "Yii",
    "Other": "Other",
});

export const MIN_TECHNOLOGIES = 1;
export const MAX_TECHNOLOGIES = 7;
