# PR Previews context: allow dev tools usage for api hostname changing, for example
[context.deploy-preview.environment]
  REACT_APP_ALLOW_DEV_TOOLS = "true"

# Branch previews context: allow dev tools usage for api hostname changing, for example
[context.branch-deploy.environment]
  REACT_APP_ALLOW_DEV_TOOLS = "true"

[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"
